config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :gist_sessions do
    resources :bookings, only: %i[create]
  end
  resources :bookings, only: %i[destroy]

  resources :users, only: %i[show] do
    resources :bookings, only: %i[index]
  end

  resources :users, only: %i[show] do
    member do
      get :aboutme
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :guest, class_name: "User"
  belongs_to :gist_session
end

app/models/gist_session.rb
class GistSession < ApplicationRecord
  validates :title, :description, :address, :start_time, :finish_time, :capacity, presence: true

  belongs_to :host, class_name: "User"
  has_many :guests, through: :bookings, foreign_key: :guest_id
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook] #  REMEMBER %i[facebook github  twitter google] etc

  def self.from_omniauth(auth)
    name_split = auth.info.name.split(" ")
    user = User.where(email: auth.info.email).first
    user ||= User.create!(provider: auth.provider, uid: auth.uid, email: auth.info.email, username: name_split[0], password: Devise.friendly_token[0, 20])
      user
  end

  has_many :gist_sessions, foreign_key: "host_id", dependent: :destroy
  has_one_attached :photo
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def create
    @booking = Booking.new(booking_date: params[:booking_date])
    @gist_session = GistSession.find(params[:gist_session_id])
    @booking.gist_session = @gist_session
    @booking.guest = current_user
    if @booking.save
      flash[:notice] = "Gist session successfully booked!"
      redirect_to user_path(current_user)
    else
      render :gist_session
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    flash[:alert] = "Booking deleted"
    redirect_to user_path(current_user)
  end
end

app/controllers/gist_sessions_controller.rb
class GistSessionsController < ApplicationController
  def index
    if params[:query].present?
      sql_query = "gist ILIKE :query"
      @gist_sessions = GistSession.where(sql_query, query: "%#{params[:query]}%")
    else
      @gist_sessions = GistSession.all
    end
  end

  def show
    @booking = Booking.new
    @gist_session = GistSession.find(params[:id])
  end

  def new
    @gist_session = GistSession.new
  end

  def create
    @gist_session = GistSession.new(gist_session_params)
    @gist_session.host = current_user
    if @gist_session.save
      flash[:notice] = "Gist Session successfully added!"
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def destroy
    @gist_session = GistSession.find(params[:id])
    @gist_session.destroy
    flash[:alert] = "Gist Session deleted"
    redirect_to user_path(current_user)
  end

  private

  def gist_session_params
    params.require(:gist_session).permit(:gist, :title, :description, :address, :start_time,
                                        :finish_time, :capacity, :host_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    flash[:error] = 'There was a problem signing you in. Please register or try signing in later.'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

app/views/gist_sessions/_form.html.erb
<div class="container">
  <%= simple_form_for @gist_session do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :start_time %>
    <%= f.input :finish_time %>
    <%= f.input :capacity %>
    <%= f.input :photo, as: :file %>
    <%= f.input :host_id, :as => :hidden %>
    <br>
    <%= f.button :submit, class: "formbtn btn" %>
  <% end %>
</div>

app/views/gist_sessions/new.html.erb
<br>
<br>
<div class="container">
  <div class="row justify-content-center">
    <div class="d-flex flex-column bd-highlight mb-3 align-items-center">
      <div class="p-2 bd-highlight" style="color: #892cdc"><h1>GREAT, GO AHEAD MATE<br> CREATE YOUR OWN GIST SESSION !</h1></div>
    </div>
    <div class="col-md-8">
        <div class="p-2 bd-highlight"><%= render 'form', gist_session: @gist_session %></div>
        <div class="p-2 bd-highlight"><%= link_to 'back to book a session', gist_sessions_path, class: "custombtn btn m-4" %></div>
    </div>
  </div>
</div>

app/views/gist_sessions/show.html.erb
<div class="container mt-4 mb-4">
  <div class="row">
    <div class="col-6">
      <%= cl_image_tag @gist_session.photo.key, crop: :fill, id:"gistpic" %>
    </div>

    <div class="col-6">

      <div class="text">
        <h1><%= @gist_session.title%></h1>
        <h4><%= @gist_session.description%></h4>
        <br>
        <div class="d-flex flex-row bd-highlight">
          <div class="bd-highlight"><p>60min --</p></div>
          <div class="bd-highlight ml-1"><p>Max <%= @gist_session.capacity%> people</p></div>
        </div>
        <p><%= @gist_session.address%></p>
        <p><strong><%= @gist_session.address%></strong></p>
      </div>

      <div class="form">
        <%= simple_form_for [ @gist_session, @booking ] do |f| %>
        <select class="form-control" name="booking_date">
          <option value="2021-01-27T12:00:00">Wednesday, Jan 27</option>
          <option value="2021-01-29T12:00:00">Friday, Jan 29</option>
          <option value="2021-02-01T12:00:00">Monday, Feb 01</option>
        </select>
        <br>
        <%= f.submit "Book me", class: "formbtn btn btn-block"%>
        <%= link_to "Changed your mind?", gist_sessions_path, class: "changemindbtn btn" %>

        <% end %>
        <br>
      </div>
    </div>
    <div class="container mt-4 border-top">
      <br>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookAndGist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="slogan-text">
    Gist anywhere, Talk to anyone
  </div>


  <div class="slogan-text-info">
    <%= link_to "Host  on-demand", new_gist_session_path, class: "calltoaction" %>
    <br>
    <%= link_to "join a group or Book one  >>", gist_sessions_path, class: "calltoaction" %>

    <br>
  </div>
</div>

<div class ="titles-box">
  <div class="home-titles">
    Most popular Gists
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm">
      <div class="card rounded" style="width: 20rem;">
        <img class="card-img-top" style="background-image: url('https://images.unsplash.com/photo-1598500229528-391c3d2c1fae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1876&q=80')">
        <div class="card-body">
          <h5 class="card-title">Hobbies</h5>
          <p class="card-text">Hobbies gists designed for real people whether you’re a busy person in need of a quick morning activity, or a someone looking to pastime before sleep. Gisting about hobbies is undertaken for pleasure or relaxation, done during one's own time. It will be so cool to talk to others about an activity that you enjoy, and that you like to spend time doing when you are not working</p>
          <a href="#" class="homebtn btn-block">More info</a>
        </div>
      </div>
    </div>
    <div class="col-sm">
      <div class="card rounded" style="width: 20rem;">
        <img class="card-img-top" style="background-image: url('https://images.unsplash.com/photo-1577896851231-70ef18881754?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80')">
        <div class="card-body">
          <h5 class="card-title">School</h5>
          <p class="card-text">A School can be an institution for educating people or any institution at which instruction is given in a particular discipline. You could gist about school with other people, help share information or learn a lot from others about schools and educational institutions. </p>
          <a href="#" class="homebtn btn-block">More info</a>
        </div>
      </div>
    </div>
    <div class="col-sm">
      <div class="card rounded" style="width: 20rem;">
        <img class="card-img-top" style="background-image: url('https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80')">
        <div class="card-body">
          <h5 class="card-title">Work</h5>
          <p class="card-text">Work is a job that you are paid for. You can gist with a group about activities involving mental or physical effort done in order to achieve a purpose or result.</p>
          <a href="#" class="homebtn btn-block">More info</a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class ="titles-box">
  <div class="home-titles">
    Hosts favourites
  </div>
</div>

<div class="container mb-4">
    <div class="row">
      <div class="col-sm">
        <div class="card rounded" style="width: 20rem;">
          <img class="card-img-top" style="background-image: url(https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1308&q=80)">
          <div class="card-body">
            <h5 class="card-title">Travel</h5>
            <p class="card-text">Traveling is to go from one place to another, typically over a distance of some length. We can gist about your experience and run everything from an average session to a fantastic session, and that it just depends on how much your host knows or how much other guests in the session know as well. We can all share and learn more.</p>
            <a href="#" class="homebtn btn-block">More info</a>
          </div>
        </div>
      </div>
      <div class="col-sm">
        <div class="card rounded" style="width: 20rem">
          <img class="card-img-top" style="background-image: url(https://images.unsplash.com/photo-1499364615650-ec38552f4f34?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1866&q=80)">
          <div class="card-body">
            <h5 class="card-title">Entertainment</h5>
            <p class="card-text">Entertainment is a form of activity that holds the attention and interest of an audience or gives pleasure and delight. It can be an idea or a task, but is more likely to be one of the activities or events that have developed over thousands of years specifically for the purpose of keeping an audience's attention. Without entertainment, we do not have any refreshments in our life. It plays a very big role in living a normal and happy life. Entertainment brings happiness, which is the most powerful medicine that helps to keep our mental health and well-being. It also means of drowning the monotony of our daily lives.</p>
            <a href="#" class="homebtn btn-block">More info</a>
          </div>
        </div>
      </div>
      <div class="col-sm">
        <div class="card rounded h-1000 w-20rem">
          <img class="card-img-top" style="background-image: url('https://images.unsplash.com/photo-1556910103-1c02745aae4d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80')">
          <div class="card-body">
            <h5 class="card-title">Cooking</h5>
            <p class="card-text">Cooking or cookery is the art, science and craft of using heat to prepare food for consumption. Cooking techniques and ingredients vary widely across the world, from grilling food over an open fire to using electric stoves, to baking in various types of ovens, reflecting unique environmental, economic, and cultural traditions and trends.

            Types of cooking also depend on the skill levels and training of cooks. Cooking is done both by people in their own dwellings and by professional cooks and chefs in restaurants and other food establishments. Cooking can also occur through chemical reactions without the presence of heat, such as in ceviche, a traditional South American dish where fish is cooked with the acids in lemon or lime juice or orange juice. Preparing food with heat or fire is an activity unique to humans. It may have started around 2 million years ago, though archaeological evidence for it reaches no more than 1 million years ago.</p>
            <a href="#" class="homebtn btn-block">More info</a>
          </div>
        </div>
      </div>
    </div>
  </div>

<div class="ad container">
  <div class="ad-text">
    YOLO
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to gist_sessions_path, class: "navbar-brand" do %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Search form -->
  <div class="searchbar-and-avatar d-flex justify-content-between">
    <div class = "searchbox-custom pr-5 pt-3">
      <div class="form-group row">
        <div class="col-10 search-form">
          <%= form_tag gist_sessions_path, method: :get do %>
            <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a gist you like !"
          %>
        </div>
        <div class="col-2 search-button">
           <%= submit_tag "Search", class: "btn searchbtn" %>
        <% end %>
        </div>
      </div>
    </div>


    <div class="collapse navbar-collapse pl-4" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown custom-avatar">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, height: 40, width: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" },'aria-haspopup': true, 'aria-expanded': false  %>
            <% else %>
              <%= image_tag "avatar_default.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Modify profile", edit_user_registration_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-sm-4">
      <div class="d-flex flex-column bd-highligh align-items-center">
        <div class="p-2 bd-highlight"><h1 class="text-center">Hello <%= @user.username %></h1></div>
        <% if @user.photo.attached? %>
          <div class="p-2 bd-highlight">
            <%= cl_image_tag @user.photo.key, crop: :fill, id: "userpic" %>
          </div>
       <% end %>
        <div class="p-2 bd-highlight">
          <div class="btn-group-vertical mt-4">
            <%= link_to "Create a session", new_gist_session_path, class: "custombtn btn mb-2" %>
            <%= link_to "Book a session/class", gist_sessions_path, class: "custombtn btn" %>
          </div>
        </div>
      </div>

    </div>
    <div class="col-sm-8">
      <div class="choice">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <a class="nav-link navlink active " id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">BOOKINGS</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link navlink" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">GIST SESSIONS</a>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade " id="home" role="tabpanel" aria-labelledby="home-tab">
      <div class="">
            <% if @user.gist_sessions == [] %>
            <div class="container mt-4">
              <p style="color: #929292;"><em>Looks like you haven’t create any classes yet<br>
                Ready to give one?</em></p>
            </div>
            <% else %>
              <% @user.gist_sessions.each do |gist_session| %>
            <div class="card m-4 sessioncard">
              <div class="card-body d-flex justify-content-between">
                <div class="date mr-3">
                  <div class="d-flex flex-column pr-4">
                    <p style="font-size: 42px"><strong><%= gist_session.start_time.strftime('%d')%></strong></p>
                    <div class="d-flex flex-row pr-4">
                      <p><%= gist_session.start_time.strftime('%b') %> 21</p>
                    </div>
                  </div>
                </div>
                <div class="flex-column align-items-left bookingdescription ml-4">
                  <h5><%= gist_session.title.upcase %></h5>
                  <p>Capacity: <%= gist_session.capacity %></p>
                  <p>$<%= gist_session.price.round %></p>
                  <p>Where: in  <%= gist_session.location%></p>
                </div>
              <br>
                <%= link_to gist_session_path(gist_session), method: :delete, data: { confirm: "Are you sure?" } do %>
                <i id="icone" class="far fa-trash-alt"></i>
                <% end %>
             </div>
            </div>

              <% end %>
            <% end %>
        </div>
    </div>
    <div class="tab-pane fade show active" id="profile" role="tabpanel" aria-labelledby="profile-tab">
      <div class="">
        <% if @bookings.nil? %>
          <div class="container">
            <p style="color: #929292;"><em>Looks like you haven’t booked any classes yet.<br>
            Ready to find one?</em></p>
          </div>
        <% elsif !@booking.nil%>
          <% @bookings.each do |booking| %>
            <div class="card m-4 sessioncard">
              <div class="card-body d-flex justify-content-between">
                <div class="date mr-3">
                  <div class="d-flex flex-column pr-4">
                    <p style="font-size: 42px"><strong><%= booking.booking_date.strftime('%d')%></strong></p>
                    <div class="d-flex flex-row pr-4">
                      <p><%= booking.booking_date.strftime('%b')%> <%= booking.booking_date.strftime('%y')%></p>
                    </div>
                  </div>
                </div>
                <div class="flex-column align-items-left bookingdescription ml-4">
                  <h5><%= booking.gist_session.title.upcase %></h5>
                  <p>With: <%= booking.gist_session.user.first_name %></p>
                  <p>Where: in  <%= booking.gist_session.location%></p>
                </div>
              <br>
              <%= link_to booking_path(booking), method: :delete, data: { confirm: "Are you sure?" } do %>
                <i id="icone" class="far fa-trash-alt"></i>
             </div>
            </div>
          <% end %>
        <% end %>
        <% end %>
        </div>
    </div>
  </div>
</div>
    </div>
  </div>
</div>
<br>
<br>